# Generated by Django 4.2.10 on 2024-03-04 16:15

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='номер телефона')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Users/', verbose_name='аватар')),
                ('verification_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='проверочный код')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='администратор сервиса')),
                ('is_staff', models.BooleanField(default=False, verbose_name='сотрудник сервиса')),
                ('is_active', models.BooleanField(default=False, verbose_name='метка активности')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('pk',),
                'permissions': [('set_is_activated', 'переключатель метки активности')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
